name: flutter_engineer_codecheck
description: "This is a code check task for Flutter engineers employment in YUMEMI."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ^3.6.1

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  yumemi_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
