# Flutterテストを自動実行するワークフロー
name: flutter-test

on: [ push ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Check out repository
        uses: actions/checkout@v4

      # Flutterの環境をセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      # 依存関係のインストール
      - name: Install dependencies
        run: flutter pub get

      # Flutterのローカライズファイルを生成します。
      - name: Generate l10n
        run: flutter gen-l10n

      # テストの実行とカバレッジの取得
      - name: Run tests
        run: flutter test --coverage
        env:
          CI: true
