# Flutterビルドを自動実行するワークフロー
name: flutter-build

on: [push]

jobs:
  build:
    name: Run Build Tests
    runs-on: ubuntu-latest

    steps:
      # ソースコードのチェックアウト
      - uses: actions/checkout@v4

      # Flutter SDKのセットアップ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      # プロジェクトの依存関係をインストール
      - name: Install dependencies
        run: flutter pub get

      # Flutterのローカライズファイルを生成します。
      - name: Generate l10n
        run: flutter gen-l10n

      # GoogleサービスのJSONファイルをデコード
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json

      # .env ファイル生成
      - name: Create .env file
        run: |
          touch .env
          echo "GITHUB_TOKEN=your_github_token_here" >> .env

      # Android ビルド用のGradleセットアップ
      - name: Setup Gradle
        run: |
          flutter create --platforms=android .
          cd android
          ./gradlew wrapper

      # Android APKのビルド
      - name: Build Android
        run: flutter build apk